#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)
# Useful script to operate my dotfiles (files starting with a "." and located at $HOME)
set +x

BASEDIR=`cd "$(dirname "$0")"; echo -n $PWD`
OP=${OP:-`basename "$0"`}

# Dot files (and other dirs/files) included in this repo, excluding some not necessary files.
DOTFILES='find "$DOTFILES_HOME"/ -maxdepth 1 ! \( -wholename "$DOTFILES_HOME"/ -o -name .git -o -name README.\* -o -name install -o -name remove -o -name .gitmodules \)'
DOTFILES_HOME_FILE=~/.dotfiles/home
DOTSTART_FILE=~/.ambiente
DOTSTART_TEMPLATE_FILE=~/.dotfiles/dotstart

sed_i() {
   case `uname` in
      Darwin) sed -i "" "$@";;
      *) sed -i "$@";;
   esac
}

_dotstart_op() {
   local readonly mark='# Load startup environment for this machine'
   local op=$1
   local profile=~/.profile
   case `uname` in
      Linux|CYGWIN*) profile=~/.bashrc;;
   esac

   [ -f $profile ] || touch $profile
   $1 $profile "$mark"
}

# Insert code on .profile (or .bashrc) to load $DOTSTART_FILE file
dotstart_install() {
   install() {
      local profile=$1
      local mark=$2
      if ! grep -q "^$mark" $profile
      then
         echo "Changing $profile to load $DOTSTART_FILE file ..."
         echo -e "$mark" >> $profile
         echo -e "f=$DOTSTART_FILE; [ -f \"\$f\" ] && source \"\$f\"; unset f" >> $profile
      fi
   }
   _dotstart_op install
}

# Remove the code from .profile (or .bashrc) that loads $DOTSTART_FILE file
dotstart_uninstall() {
   uninstall() {
      local profile=$1
      local mark=$2

      sed_i "/^$mark/{N;d;}" $profile
   }
   _dotstart_op uninstall
}

# Do an operation at files specified by $DOTFILES
_dotfiles() {
   local f
   local t
   local op=$1
   
   for f in `eval $DOTFILES`
   do
      f=${f##*/}

      if [ -L "$DOTFILES_HOME/$f" ]
      then
         t=link
      elif [ -f "$DOTFILES_HOME/$f" ]
      then
         t=file
      elif [ -d "$DOTFILES_HOME/$f" ]
      then
         t=dir
      else
         continue
      fi

      $op $f $t
   done
}

# Install a file at ~/
_install() {
   local f=$1
   local t=$2

   case "$f" in
      .dotfiles|.gitignore)
      echo "Skipping $t $f"
      return
      ;;
   esac

   case $OSTYPE in
      cygwin)
         echo "Copying $t $DOTFILES_HOME/$f to ~/"
         cp -r "$DOTFILES_HOME/$f" ~/
      ;;
      *)
         echo "Linking $t $DOTFILES_HOME/$f to ~/$f"
         ln -s "${DOTFILES_HOME/$HOME\/}/$f" ~/
      ;;
   esac
}

# Remove a file from ~/
_remove() {
   local f=$1
   local t=$2
   
   echo "Unlinking $t ~/$f"
   case $OSTYPE in
		cygwin)
			rm -rf ~/$f
		;;
		*)
			rm -f ~/$f
		;;
   esac
}

# Processing starts here ...
if [ "$OP" = "install" ]
then
   echo "Installing dotfiles ..."
   if ! [ "$DOTFILES_HOME" ]
   then
      export DOTFILES_HOME=$BASEDIR

      case $OSTYPE in
         cygwin)
            cp -r "$DOTFILES_HOME"/.dotfiles ~/
         ;;
         *) 
            ln -s "${DOTFILES_HOME/$HOME\/}/.dotfiles" ~/
         ;;
      esac
      echo "Writing $DOTFILES_HOME_FILE with the following content:"
      echo "export DOTFILES_HOME=\"$DOTFILES_HOME\"" | tee $DOTFILES_HOME_FILE
   fi

   dotstart_install
else
   echo "Removing dotfiles ..."
fi

if [ ! "$DOTFILES_HOME" ]
then
   echo "DOTFILES_HOME variable must be configured to use this script! Nothing to do!"
   exit 1
fi

# do operation
_dotfiles _$OP

# pos-operations
if [ "$OP" = "install" ]
then 
   if [ -f "$DOTSTART_FILE" ]
   then
      BACKUP="$DOTSTART_FILE".`date "+%Y%m%d-%H%M%S"`
      echo "File \"$DOTSTART_FILE\" exists! Moving it to \"$BACKUP\"!"
      mv "$DOTSTART_FILE" "$BACKUP"
   else
      echo "File \"$DOTSTART_FILE\" does not exists! Creating it from \"$DOTSTART_TEMPLATE_FILE\"!"
   fi
   sed "s,DOTSTART_FILE,$DOTSTART_FILE,g" $DOTSTART_TEMPLATE_FILE > $DOTSTART_FILE
   echo "Files installed! For effect, you need to restart your shell!"
   #case $OSTYPE in
   #   cygwin) $BASEDIR/.scripts/fixvim;;
   #esac
else
   dotstart_uninstall
   echo "Files removed! For effect, you need to restart your shell!";
fi

# vim: set ts=3 sw=3 expandtab:
