#!/usr/bin/env bash

settings_dir=~/.company/Settings
proxy_file=$settings_dir/proxy.sh
docker_file=$settings_dir/docker.sh

DOCKER_COMPOSE_RELEASE=${DOCKER_COMPOSE_RELEASE:-'1.28.2'}
source_file() {
    source "$1" &> /dev/null || {
        echo "File \"$1\" could not be read!"
        return $?
    }
}
