#!/usr/bin/env bash

apt_packages=(
	chromium-browser
	curl
	lynx
	tree
	vim
	w3m
)

snap_packages=(
	"intellij-idea-community --classic"
	"kotlin --classic"
)

ruby_packages=(
	"asciidoctor-pdf --pre"
)

apt-packages-install() {
    sudo apt update
    sudo apt install -y ${apt_packages[*]}
}

cat > /dev/null << TO_BE_FIXED
snap-packages-install() {
    for snap_package in "${snap_packages[@]}"
    do
        snap install "$snap_package"
    done
}
TO_BE_FIXED

cat > /dev/null << TO_BE_FIXED
ruby-packages-install() {
    for ruby_package in "${ruby_packages[@]}"
    do
        sudo gem install --http-proxy $http_proxy "$ruby_package"
    done
}
TO_BE_FIXED

apt-packages-install
#ruby-packages-install
