#!/usr/bin/env bash
set -eou pipefail

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR/config"

sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_RELEASE}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
