#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)
#
# This script clones a CentOS public mirror to use as a private 
# mirror in my teaching classes about Linux, JBoss and related 
# things.
#
# Some alternative mirrors (near to Brazil)
#
#rsync://linorg.usp.br/CentOS/6.4/ mirror/6.4
#rsync://mirrors.abdicar.com/costarica_CentOS/6.4/ mirror/6.4
#rsync://centos.ufms.br/CentOS/6.4/ mirror/6.4

d=${CENTOS_HOME:-~/Work/CentOS}
mkdir -p $d/mirror && cd $d

# This will rsync only CentOS i386 and exclude x86_64
rsync --progress -avrt --delete --delete-excluded \
--include "isos/i386/CentOS-6.4-i386-netinstall.iso" \
--exclude "isos/i386/*" \
--exclude "isos/x86_64" \
--exclude "local*" \
--exclude "centosplus" \
--exclude "x86_64" \
rsync://linorg.usp.br/CentOS/6.4/ mirror/6.4

cd mirror

[ -L 6 ] || ln -s 6.4 6
