#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)
# Useful script operate dotfiles (files starting with a "." and located at $HOME)

# Do an operation at files specified by $DOTFILES
_dotfiles() {
   local f
   local t
   local op=$1

   for f in `eval $DOTFILES`
   do
      f=${f##*/}

      if [ -f "$f" ]
      then
         t=file
      elif [ -L "$f" ]
      then
         t=link
      else
         t=dir
      fi

      $op $f $t
   done
}

# Show a file and its type (file or dir)
_list() {
   local f=$1
   local t=$2

   echo "$f ($t)"
}

# Install a file at ~/
_install() {
   local f=$1
   local t=$2

   echo "Installing $t $f at ~/ from $DOTFILES_HOME ..."

   rm -rf ~/$f
   cp -a $DOTFILES_HOME/$f ~/
}

# Show differences between a file at ~/ and its original in $DOTFILES_HOME/
_diff() {
   local f=$1
   local t=$2

   echo "Diff between ~/$f and $DOTFILES_HOME/$f ..."
   diff -uNr ~/$f $DOTFILES_HOME/$f
}

# Update a file from ~/ to $DOTFILES_HOME/
_update() {
   local f=$1
   local t=$2

   echo -n "Updating $t $DOTFILES_HOME/$f from ~/ ... "

   if [ "$t" = "file" ]
   then
      [ ~/$f -nt $DOTFILES_HOME/$f ] && { cp -af ~/$f $DOTFILES_HOME/; echo 'done!'; } || echo 'skipped!'
   else
      rsync -av --update --delete ~/$f $DOTFILES_HOME/
   fi
}

# Remove a file from ~/
_remove() {
   local f=$1
   local t=$2
   
   echo "Removing $t ~/$f ..."
   rm -rf ~/$f
}

# Dot files (and other dirs/files) included in this repo, excluding README.* files and .git dir.
DOTFILES='find $DOTFILES_HOME -maxdepth 1 ! \( -path $DOTFILES_HOME -o -wholename $DOTFILES_HOME -o -name .git -o -name README.\* -o -name install -o -name remove \)'

# Sample dot file used to create $DOTSTART_FILE if it does'nt exists
SAMPLE_DOTSTART_FILE=~/.sample-dotstart

OP=$1
OPTS='list|install|diff|update|remove'
DF=~/.dotfiles

[ "$OP" ] || { echo "You must specify one of the options: $OPTS"; exit 1; }

case $OP in
   dir) 
      echo "DOTFILES_HOME=$DOTFILES_HOME"
      exit 0
      ;;
   list|install|diff|update|remove)
      # pre-operations
      if [ "$OP" = "install" ]
      then
         if ! [ "$DOTFILES_HOME" ]
         then
            DOTFILES_HOME=`cd $(dirname $0)/..; echo -n $PWD`
            echo "Writing $DF with the following content:"
            echo "export DOTFILES_HOME=$DOTFILES_HOME" > $DF
            cat $DF
         fi

         f="$DOTFILES_HOME/.my-functions"
         if [ -f "$f" ]
         then
            source "$f" && dotstart_install
         fi
      fi

      if [ ! "$DOTFILES_HOME" ]
      then
         echo "You must configure DOTFILES_HOME to use this script! Nothing to do!"
         exit 1
      fi

      # do operation
      _dotfiles _$OP

      # pos-operations
      if [ "$OP" = "install" ]
      then 
         if [ -f "$DOTSTART_FILE" ]
         then
            echo "File \"$DOTSTART_FILE\" exists! Using it!"
         else
            echo "File \"$DOTSTART_FILE\" does not exists! Creating it from \"$SAMPLE_DOTSTART_FILE\"!"
            cp -a "$SAMPLE_DOTSTART_FILE" "$DOTSTART_FILE"
         fi
         echo "Files installed! Remember to restart your shell!"
      fi

      if [ "$OP" = "remove" ]
      then
         echo "Removing file $DF ..."
         rm $DF; 
         echo "Files removed!"; 
      fi
      ;;
   *) 
      echo "\"$OP\" is an invalid option!"
      ;;
esac
