#!/bin/bash
# Autor: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

BIN_DIR=`dirname $0`

source "$BIN_DIR/funcoes-instalar"

script=`basename "$0"`; app=`echo -n ${script#remover-}`
[ "$app" = "remover" ] && { [ "$1" ] && { app="$1"; shift; } || falha "Aplicação não informada!"; }
remove $app "$@"
