#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)
#
# Arquivo DOTSTART_FILE (gerado a partir do .dotfiles/dotstart)

# Habilita mais mensagens se configurado para true
# Configure aqui, ou antes num dos arquivos de inicialização (~/.bashrc, ~/.profile)
VERBOSO=${VERBOSO:-false}

# Carrega variáveis e funções
f=~/.dotfiles/home; source $f || return $?
f=~/.funcoes/diversas.sh; source $f || return $?
carregar_arquivos_em ~/.{configuracoes,funcoes}{,/$PLATAFORMA} -i $f
unset f

# Configura o PATH
[[ $PLATAFORMA = Cygwin ]] && export PATH=~/bin:$PATH
export PATH=~/.scripts:~/.scripts/docker:$PATH
[[ $PLATAFORMA = Linux ]] && export PATH=~/.scripts/`distro`:$PATH

# Ajusta e carrega o ambiente (se ele não for /dev/null)
export ENVIRONMENT=/dev/null
[ "$ENVIRONMENT" != /dev/null ] && [ -f "$ENVIRONMENT" ] && source "$ENVIRONMENT"

# Apresenta a data e a hora da sessão (se estivermos num login shell)
shopt -q login_shell && date +"Sessão iniciada em %F às %T"

# Start TMUX (Ref: https://unix.stackexchange.com/a/113768)
command -v tmux &> /dev/null && \
    [ -n "$PS1" ] && \
    [[ ! "$TERM" =~ screen ]] && \
    [[ ! "$TERM" =~ tmux ]] && \
    [ -z "$TMUX" ] && \
    exec tmux
