#!/usr/bin/env bash
set -eou pipefail
BASE_DIR=`cd "$(dirname "$0")"; pwd -P`
SCRIPT=${0##*/}
GISTS_DIR=$BASE_DIR/gists
DIR_NAME=${GISTS_DIR#$BASE_DIR/}
[[ ( "${1:-}" != refresh ) && ( -d "$GISTS_DIR" ) ]] && {
	echo $DIR_NAME
	exit 0
}
[ -f ~/.$SCRIPT ] || (cd; d=${BASE_DIR#$HOME/}; d=${d%/*}; ln -s "$d"/.$SCRIPT)
rm -rf "$GISTS_DIR"; mkdir -p "$_"; cd "$_"
while IFS= read gist; do git clone https://gist.github.com/$gist; done < ~/.$SCRIPT
[[ $OSTYPE =~ darwin ]] && executables='-perm 755' || executables='-executable'
for bin in $(find . -maxdepth 2 \( -type f -o -type l \) $executables); do ln -s $bin; done
echo $DIR_NAME
