#!/usr/bin/env bash
set +x

PLAYLISTS=playlists.txt

[ "$1" = "-f" ] && {
  shift
  PLAYLISTS=$1
}

[ -f "$PLAYLISTS" ] || {
  echo "File \"$PLAYLISTS\" not found!"
  exit 0
}

while read playlist
do
  #https://github.com/ytdl-org/youtube-dl#options
  youtube-dl -co '%(playlist)s/%(playlist_index)s - %(title)s-%(id)s.%(ext)s' "$playlist"
done < "$PLAYLISTS"
