#!/bin/bash
# Autor: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)
#
# Funções auxiliares para relativas a montagem de um ambiente

# no arquivo de inicialização do shell
instalar_ambiente() {
  local profile

  # no OS X (Darwin), o arquivo inicializado a cada novo shell é o ~/.profile
  # no Linux e no Cygwin, o arquivo é o ~/.bashrc
  $DARWIN && profile=~/.profile || profile=~/.bashrc

  grep '^# carrega.*ambiente$' $profile &> /dev/null && return 0
  cat >> $profile <<EOF

# carrega o ambiente
f=~/$AMBIENTE_DIR/ambiente; [ -f \$f ] && source \$f; unset f
EOF
}

# Remove o cache local de instaladores
remover_instaladores() {
  rm -rf "$INSTALADORES_DIR"
}

# Remove o diretório das ferramentas
remover_ferramentas() {
  rm -rf "$FERRAMENTAS_DIR"
}

# Recupera um diretório de instaladores salvo, caso ele exista e não haja um diretório instaladores existente
#   esta recuperação só é funciona se os instaladores estiverem no sistema de arquivos da máquina e 
#   este procedimento apenas gerará um link para a localização do instalador neste sistema de arquivos
recuperar_instaladores() {
  local instaladores=`basename $INSTALADORES_DIR`
  local bkp_instaladores="$AMBIENTE_HOME.instaladores"

  pushd "$AMBIENTE_HOME" &> /dev/null
  if [ -d "$bkp_instaladores" -a ! -d $instaladores ]; then
    mkdir $instaladores
    pushd $instaladores &> /dev/null
    local f
    for f in "$bkp_instaladores"/*; do
      ln -s $f
    done
    popd &> /dev/null
  fi
  popd &> /dev/null
}

# Salvar os instaladores que estiverem no cache e não estiverem no diretório de instaladores salvos
salvar_instaladores() {
  local bkp_instaladores="$AMBIENTE_HOME.instaladores"

  if [ -d "$INSTALADORES_DIR" ]; then
    pushd "$INSTALADORES_DIR" &> /dev/null
    local f
    [ -d "$bkp_instaladores" ] || mkdir -p "$bkp_instaladores"
    for f in `find . -type f`; do
      cp -f "$f" "$bkp_instaladores"
    done
    popd &> /dev/null
  fi
}

# Desabilita regras de firewall no iptables.
#   Esta função deve ser chamada antes de testar o cluster pois,
#   caso contrário, os nós do cluster não se encontrarão.   
firewall_desabilitar() {
  sudo iptables -F
}

# A chamada desta função neste ponto recupera o diretório instaladores no carregar deste arquivo!
#   Isto não é necessário mas, neste ambiente, está sendo utilizado para poupar espaço no disco da VM 
#   já que os instaladores já estão todos nela (~/curso-jboss.instaladores)
recuperar_instaladores

# Carrega variáveis inicializadas por ambiente
DARWIN=false
LINUX=false
CYGWIN=false
case `uname` in
  Darwin) DARWIN=true;;
  Linux) LINUX=true;;
  CYGWIN*) CYGWIN=true;;
esac
