#!/bin/bash
BASE_DIR=`cd "$(dirname "$0")"; pwd`
DEST_DIR=${DEST_DIR:-~/Music/from-movies/`basename "$PWD"`}

# http://askubuntu.com/a/344418
IFS=$'\n'

_do4() {
  local t=$1

  echo "Converting *.$t from $PWD to \"$DEST_DIR\" ..."
  for f in $(find . -type f -name "*.$t")
  do
    f=${f#*/}
    dest=$DEST_DIR/${f%.$t}.mp3
    [ -f "$dest" ] && { echo "Skipping \"$f\" ..."; continue; }
    echo "Converting \"$f\" ..."
    mkdir -p "$DEST_DIR/`dirname "$f"`"
    case "$t" in
      m4a)
        ffmpeg -i "$f" -c:a libmp3lame -q:a 1 "$dest" 2> /dev/null
        ;;
      mp4)
        # http://bit.ly/2mfcSSK
        ffmpeg -i "$f" -b:a 192K -vn "$dest" 2> /dev/null
        ;;
    esac
  done
}

_m4a() {
  _do4 m4a
}

_mp4() {
  _do4 mp4
}

op=${1:-mp4}
if type _$op &> /dev/null
then
  [ -d "$DEST_DIR" ] || echo "Creating \"$DEST_DIR\" ..."
  mkdir -p "$DEST_DIR"
  _$op
fi
