#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

case `uname` in
  Linux) 
    BIN=/usr/bin/ssh-copy-id
    [ -x $BIN ] && { $BIN "$@"; exit $?; }
    ;;
esac

KEY="$HOME/.ssh/id_rsa.pub"
SSH_PARAMS=$@

[ ! -f $KEY ] && { echo "I can't find the key \"$KEY\". Please, generate it!"; exit; }
[ "$SSH_PARAMS" ] || { echo "No parameters specified. Nothing to do!"; exit; }

cat $KEY | ssh $SSH_PARAMS '
   f=~/.ssh/authorized_keys; d=`dirname $f`
   mkdir -p $d; chmod 700 $d
   cat - >> $f; chmod 640 $f
'

# vim: set ts=2 sw=2 expandtab:
