#!/usr/bin/env bash

# https://stackoverflow.com/a/21189044
function parse_yaml {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}

for f in course.yaml cookies.txt
do
  if ! [ -f $f ]
  then
    echo "File \"$f\" not available in \"${PWD}\"!"
    exit 1
  fi
done

eval $(parse_yaml course.yaml)

FILE_NAME_FORMAT='%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s'

# https://gist.github.com/barbietunnie/8531d9c26cd1c0668e7278c7c4ba5853
youtube-dl --cookies ./cookies.txt -o "$FILE_NAME_FORMAT" $course_uri
